interface IObjectKeys {
	[key: string]: string | number | any;
}

export const permissionsConfig: IObjectKeys = {
	actors: {
		list: 'actors.list',
		create: 'actors.create',
		edit: 'actors.edit',
		update: 'actors.update',
		delete: 'actors.delete',
		restore: 'actors.restore',
	},
	genres: {
		list: 'genres.list',
		create: 'genres.create',
		edit: 'genres.edit',
		update: 'genres.update',
		delete: 'genres.delete',
		restore: 'genres.restore',
	},
	room_status: {
		list: 'room_status.list',
		// create: 'room_status.create',
		// edit: 'room_status.edit',
		// update: 'room_status.update',
		// delete: 'room_status.delete',
		// restore: 'room_status.restore',
	},
	items: {
		list: 'items.list',
		create: 'items.create',
		edit: 'items.edit',
		update: 'items.update',
		delete: 'items.delete',
		restore: 'items.restore',
	},
	rooms: {
		list: 'rooms.list',
		create: 'rooms.create',
		edit: 'rooms.edit',
		update: 'rooms.update',
		delete: 'rooms.delete',
		restore: 'rooms.restore',
	},
	seats: {
		list: 'seats.list',
		create: 'seats.create',
		edit: 'seats.edit',
		update: 'seats.update',
		delete: 'seats.delete',
		restore: 'seats.restore',
	},
	role: {
		list: 'role.list',
		create: 'role.create',
		edit: 'role.edit',
		update: 'role.update',
		delete: 'role.delete',
		restore: 'role.restore',
	},
	directors: {
		list: 'directors.list',
		create: 'directors.create',
		edit: 'directors.edit',
		update: 'directors.update',
		delete: 'directors.delete',
		restore: 'directors.restore',
	},
	employee: {
		list: 'employee.list',
		create: 'employee.create',
		edit: 'employee.edit',
		update: 'employee.update',
		delete: 'employee.delete',
		restore: 'employee.restore',
	},
	age_ratings: {
		list: 'age_ratings.list',
		// create: 'age_ratings.create',
		// edit: 'age_ratings.edit',
		// update: 'age_ratings.update',
		// delete: 'age_ratings.delete',
		// restore: 'age_ratings.restore',
	},
	movies: {
		list: 'movies.list',
		create: 'movies.create',
		edit: 'movies.edit',
		update: 'movies.update',
		delete: 'movies.delete',
		restore: 'movies.restore',
	},
	movie_directors: {
		list: 'movie_directors.list',
		create: 'movie_directors.create',
		edit: 'movie_directors.edit',
		update: 'movie_directors.update',
		delete: 'movie_directors.delete',
		restore: 'movie_directors.restore',
	},
	movie_genres: {
		list: 'movie_genres.list',
		create: 'movie_genres.create',
		edit: 'movie_genres.edit',
		update: 'movie_genres.update',
		delete: 'movie_genres.delete',
		restore: 'movie_genres.restore',
	},
	movie_actors: {
		list: 'movie_actors.list',
		create: 'movie_actors.create',
		edit: 'movie_actors.edit',
		update: 'movie_actors.update',
		delete: 'movie_actors.delete',
		restore: 'movie_actors.restore',
	},
	customer_types: {
		list: 'customer_types.list',
		create: 'customer_types.create',
		edit: 'customer_types.edit',
		update: 'customer_types.update',
		delete: 'customer_types.delete',
		restore: 'customer_types.restore',
	},
	customers: {
		list: 'customers.list',
		create: 'customers.create',
		edit: 'customers.edit',
		update: 'customers.update',
		delete: 'customers.delete',
		restore: 'customers.restore',
	},
};
