interface IObjectKeys {
	[key: string]: string | number | any;
}

export const permissionsConfig: IObjectKeys = {
	actors: {
		name: "Diễn viên",
		list: 'actors.list',
		create: 'actors.create',
		edit: 'actors.edit',
		update: 'actors.update',
		delete: 'actors.delete',
		restore: 'actors.restore',
	},
	genres: {
		name: "Thể loại",
		list: 'genres.list',
		create: 'genres.create',
		edit: 'genres.edit',
		update: 'genres.update',
		delete: 'genres.delete',
		restore: 'genres.restore',
	},
	room_status: {
		name: "Trạng thái phòng",
		list: 'room-status.list',
		// create: 'room-status.create',
		// edit: 'room-status.edit',
		// update: 'room-status.update',
		// delete: 'room-status.delete',
		// restore: 'room-status.restore',
	},
	items: {
		name: "Thức ăn",
		list: 'items.list',
		create: 'items.create',
		edit: 'items.edit',
		update: 'items.update',
		delete: 'items.delete',
		restore: 'items.restore',
	},
	rooms: {
		name: "Phòng chiếu",
		list: 'rooms.list',
		create: 'rooms.create',
		edit: 'rooms.edit',
		update: 'rooms.update',
		delete: 'rooms.delete',
		restore: 'rooms.restore',
	},
	seats: {
		name: "Ghế",
		list: 'seats.list',
		create: 'seats.create',
		edit: 'seats.edit',
		update: 'seats.update',
		delete: 'seats.delete',
		restore: 'seats.restore',
	},
	role: {
		name: "Vai trò",
		list: 'role.list',
		create: 'role.create',
		edit: 'role.edit',
		update: 'role.update',
		delete: 'role.delete',
		restore: 'role.restore',
	},
	directors: {
		name: "Đạo diễn",
		list: 'directors.list',
		create: 'directors.create',
		edit: 'directors.edit',
		update: 'directors.update',
		delete: 'directors.delete',
		restore: 'directors.restore',
	},
	employee: {
		name: "Nhân viên",
		list: 'employee.list',
		create: 'employee.create',
		edit: 'employee.edit',
		update: 'employee.update',
		delete: 'employee.delete',
		restore: 'employee.restore',
	},
	age_ratings: {
		name: "Đánh giá tuổi",
		list: 'age-ratings.list',
		// create: 'age-ratings.create',
		// edit: 'age-ratings.edit',
		// update: 'age-ratings.update',
		// delete: 'age-ratings.delete',
		// restore: 'age-ratings.restore',
	},
	movies: {
		name: "Phim",
		list: 'movies.list',
		create: 'movies.create',
		edit: 'movies.edit',
		update: 'movies.update',
		delete: 'movies.delete',
		restore: 'movies.restore',
	},
	movie_directors: {
		name: "Đạo diễn phim",
		list: 'movie-directors.list',
		create: 'movie-directors.create',
		edit: 'movie-directors.edit',
		update: 'movie-directors.update',
		delete: 'movie-directors.delete',
		restore: 'movie-directors.restore',
	},
	movie_genres: {
		name: "Thể loại phim",
		list: 'movie-genres.list',
		create: 'movie-genres.create',
		edit: 'movie-genres.edit',
		update: 'movie-genres.update',
		delete: 'movie-genres.delete',
		restore: 'movie-genres.restore',
	},
	movie_actors: {
		name: "Diễn viên phim",
		list: 'movie-actors.list',
		create: 'movie-actors.create',
		edit: 'movie-actors.edit',
		update: 'movie-actors.update',
		delete: 'movie-actors.delete',
		restore: 'movie-actors.restore',
	},
	customer_types: {
		name: "Loại khách hàng",
		list: 'customer-types.list',
		create: 'customer-types.create',
		edit: 'customer-types.edit',
		update: 'customer-types.update',
		delete: 'customer-types.delete',
		restore: 'customer-types.restore',
	},
	customers: {
		name: "Khách hàng",
		list: 'customers.list',
		create: 'customers.create',
		edit: 'customers.edit',
		update: 'customers.update',
		delete: 'customers.delete',
		restore: 'customers.restore',
	},
	orders: {
		name: "Đơn hàng",
		list: 'orders.list',
		create: 'orders.create',
		edit: 'orders.edit',
		update: 'orders.update',
		delete: 'orders.delete',
		restore: 'orders.restore',
	},
	blogs: {
		name: "Tin tức",
		list: 'blogs.list',
		create: 'blogs.create',
		edit: 'blogs.edit',
		update: 'blogs.update',
		delete: 'blogs.delete',
		restore: 'blogs.restore',
	},
	categories: {
		name: "Thể loại tin tức",
		list: 'categories.list',
		create: 'categories.create',
		edit: 'categories.edit',
		update: 'categories.update',
		delete: 'categories.delete',
		restore: 'categories.restore',
	},
	combo: {
		name: "Combo",
		list: 'combo.list',
		create: 'combo.create',
		edit: 'combo.edit',
		update: 'combo.update',
		delete: 'combo.delete',
		restore: 'combo.restore',
	},
	combo_tickets: {
		name: "Combo vé",
		list: 'combo_tickets.list',
		create: 'combo_tickets.create',
		edit: 'combo_tickets.edit',
		update: 'combo_tickets.update',
		delete: 'combo_tickets.delete',
		restore: 'combo_tickets.restore',
	},
	movie_tickets: {
		name: "Vé phim",
		list: 'movie_tickets.list',
		create: 'movie_tickets.create',
		edit: 'movie_tickets.edit',
		update: 'movie_tickets.update',
		delete: 'movie_tickets.delete',
		restore: 'movie_tickets.restore',
	},
	payments: {
		name: "Thanh toán",
		list: 'payments.list',
		create: 'payments.create',
		edit: 'payments.edit',
		update: 'payments.update',
		delete: 'payments.delete',
		restore: 'payments.restore',
	},
	seat_status: {
		name: "Trạng thái ghế",
		list: 'seat-status.list',
		create: 'seat-status.create',
		edit: 'seat-status.edit',
		update: 'seat-status.update',
		delete: 'seat-status.delete',
		restore: 'seat-status.restore',
	},
};
